<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic Condition="'$(Configuration)' == 'Release'">true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Deed.Core/Deed.Core.csproj" />
  </ItemGroup>
</Project>
